### ISSUE TITLE
license.key should be removed from repository

### ISSUE THREAD

**Issue by alexwybraniec** [madebyshape/craft-3#24]
Hello, 

If you have license.key in your repository, and someone clones your repos and then goes on to register the repository key with a paid license, all project using that repository key can see any registered plugins and could potentially 'steal' the license.

license.key only gets regenerated on installation when the file is not present.

https://craftcms.com/knowledge-base/more-information-than-you-require-about-craft-license-keys#gotchas

We know this because we made the same mistake in our boilerplate repos, and now we're having to transfer and refund licenses to move them between keys :-(

This was the first repos we found with the same issue so we're doing the right thing and passing on the knowledge.

Alex W

**Comment by bymayo** [comment]
@alexwybraniec Thanks for the heads up on this. We've only recently made this change luckily.

The reason we did this was because we can't buy plugins on production, so are having to do them locally. This means that we buy them locally, and deploy the license key.

Whats your current workaround for this?

**Comment by alexwybraniec** [comment]
Hi @bymayo 

Buying them locally is fine, and we are in the same position, but each project needs to have a unique license.key, and this won't be generated on install if the file is present in your boilerplate project.

You may be deleting this file and generating that key already, but we weren't aware of the issue above and hence we ran into problems where a project for one client suddenly included the paid plugin details of another client.

Earlier today, when we were looking at the issue, I was able to add your license.key from this project to my Craft ID account, and had you (or someone who had started a project from this repository) had any paid plugins attached to that key, I would have been able to see their licensing details and possible use them without paying.

I spoke to Craft today and confirmed that if the contents of license.key are public, it should be regenerate and any licenses should be reattached to a new key.

**Comment by bymayo** [comment]
@alexwybraniec Gotcha. I think we should be okay as I only recently made this change. But I'll double check, as I doubt any projects using that key have gone live. 

I've deleted the key from this project now, so that shouldn't be a problem for future projects.

Again, thanks for letting me know about this, appreciate it 🤙
